-- MySQL Script generated by MySQL Workbench
-- Fri Mar 31 11:21:44 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Bruger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bruger` (
  `idBruger` INT NOT NULL AUTO_INCREMENT,
  `Navn` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Adgangskode` VARCHAR(45) NOT NULL,
  `Adresse` VARCHAR(45) NOT NULL,
  `Postnummer` INT NOT NULL,
  `By` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBruger`, `Navn`, `Adresse`, `Postnummer`, `By`),
  UNIQUE INDEX `idBruger_UNIQUE` (`idBruger` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Abonnementer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Abonnementer` (
  `idOdre` INT NOT NULL AUTO_INCREMENT,
  `Betalt` INT NOT NULL DEFAULT 0,
  `TotalPris` DECIMAL(6,2) NOT NULL DEFAULT 0,
  `Bruger_idBruger` INT NOT NULL,
  `Bruger_Navn` VARCHAR(45) NOT NULL,
  `Bruger_Adresse` VARCHAR(45) NOT NULL,
  `Bruger_Postnummer` INT NOT NULL,
  `Bruger_By` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOdre`, `Bruger_idBruger`, `Bruger_Navn`, `Bruger_Adresse`, `Bruger_Postnummer`, `Bruger_By`),
  UNIQUE INDEX `idOdre_UNIQUE` (`idOdre` ASC),
  INDEX `fk_Abonnementer_Bruger1_idx` (`Bruger_idBruger` ASC, `Bruger_Navn` ASC, `Bruger_Adresse` ASC, `Bruger_Postnummer` ASC, `Bruger_By` ASC),
  CONSTRAINT `fk_Abonnementer_Bruger1`
    FOREIGN KEY (`Bruger_idBruger` , `Bruger_Navn` , `Bruger_Adresse` , `Bruger_Postnummer` , `Bruger_By`)
    REFERENCES `mydb`.`Bruger` (`idBruger` , `Navn` , `Adresse` , `Postnummer` , `By`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produkter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produkter` (
  `idProdukter` INT NOT NULL AUTO_INCREMENT,
  `Pakkenavn` VARCHAR(45) NOT NULL,
  `Billede` VARCHAR(45) NULL,
  `Indhold` VARCHAR(45) NOT NULL,
  `Pris` DECIMAL(6,2) NOT NULL,
  `Abonnementer_idOdre` INT NOT NULL,
  PRIMARY KEY (`idProdukter`, `Abonnementer_idOdre`),
  UNIQUE INDEX `idProdukter_UNIQUE` (`idProdukter` ASC),
  INDEX `fk_Produkter_Abonnementer1_idx` (`Abonnementer_idOdre` ASC),
  CONSTRAINT `fk_Produkter_Abonnementer1`
    FOREIGN KEY (`Abonnementer_idOdre`)
    REFERENCES `mydb`.`Abonnementer` (`idOdre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
